export const TEST_CONTACTS = [
  {
    firstName: "Shruti",
    lastName: "Kapoor",
    avatarUrl: "https://sessionize.com/image/124e-400o400o2-wHVdAuNaxi8KJrgtN3ZKci.jpg",
    email: "shrutikapoor08@some.com",
  },
  {
    firstName: "Glenn",
    lastName: "Reyes",
    avatarUrl: "https://sessionize.com/image/1940-400o400o2-Enh9dnYmrLYhJSTTPSw3MH.jpg",
    email: "glnnrys@some.com",
  },
  {
    firstName: "Ryan",
    lastName: "Florence",
    avatarUrl: "https://sessionize.com/image/9273-400o400o2-3tyrUE3HjsCHJLU5aUJCja.jpg",
    email: "r.f@some.com",
  },
  {
    firstName: "Oscar",
    lastName: "Newman",
    avatarUrl: "https://sessionize.com/image/d14d-400o400o2-pyB229HyFPCnUcZhHf3kWS.png",
    email: "oscarnewman@some.com",
  },
  {
    firstName: "Michael",
    lastName: "Jackson",
    avatarUrl: "https://sessionize.com/image/fd45-400o400o2-fw91uCdGU9hFP334dnyVCr.jpg",
    email: "m.j@some.com",
  },
  {
    firstName: "Christopher",
    lastName: "Chedeau",
    avatarUrl: "https://sessionize.com/image/b07e-400o400o2-KgNRF3S9sD5ZR4UsG7hG4g.jpg",
    email: "Vjeux@some.com",
  },
  {
    firstName: "Cameron",
    lastName: "Matheson",
    avatarUrl: "https://sessionize.com/image/262f-400o400o2-UBPQueK3fayaCmsyUc1Ljf.jpg",
    email: "cmatheson@some.com",
  },
  {
    firstName: "Brooks",
    lastName: "Lybrand",
    avatarUrl: "https://sessionize.com/image/820b-400o400o2-Ja1KDrBAu5NzYTPLSC3GW8.jpg",
    email: "BrooksLybrand@some.com",
  },
  {
    firstName: "Alex",
    lastName: "Anderson",
    avatarUrl: "https://sessionize.com/image/df38-400o400o2-JwbChVUj6V7DwZMc9vJEHc.jpg",
    email: "ralex1993@some.com",
  },
  {
    firstName: "Kent C.",
    lastName: "Dodds",
    avatarUrl: "https://sessionize.com/image/5578-400o400o2-BMT43t5kd2U1XstaNnM6Ax.jpg",
    email: "kentcdodds@some.com",
  },
  {
    firstName: "Nevi",
    lastName: "Shah",
    avatarUrl: "https://sessionize.com/image/c9d5-400o400o2-Sri5qnQmscaJXVB8m3VBgf.jpg",
    email: "nevikashah@some.com",
  },
  {
    firstName: "Andrew",
    lastName: "Petersen",
    avatarUrl: "https://sessionize.com/image/2694-400o400o2-MYYTsnszbLKTzyqJV17w2q.png",
    email: "a.p@some.com",
  },
  {
    firstName: "Scott",
    lastName: "Smerchek",
    avatarUrl: "https://sessionize.com/image/907a-400o400o2-9TM2CCmvrw6ttmJiTw4Lz8.jpg",
    email: "smerchek@some.com",
  },
  {
    firstName: "Giovanni",
    lastName: "Benussi",
    avatarUrl: "https://sessionize.com/image/08be-400o400o2-WtYGFFR1ZUJHL9tKyVBNPV.jpg",
    email: "giovannibenussi@some.com",
  },
  {
    firstName: "Igor",
    lastName: "Minar",
    avatarUrl: "https://sessionize.com/image/f814-400o400o2-n2ua5nM9qwZA2hiGdr1T7N.jpg",
    email: "IgorMinar@some.com",
  },
  {
    firstName: "Brandon",
    lastName: "Kish",
    avatarUrl: "https://sessionize.com/image/fb82-400o400o2-LbvwhTVMrYLDdN3z4iEFMp.jpeg",
    email: "b.k@some.com",
  },
  {
    firstName: "Arisa",
    lastName: "Fukuzaki",
    avatarUrl: "https://sessionize.com/image/fcda-400o400o2-XiYRtKK5Dvng5AeyC8PiUA.png",
    email: "arisa_dev@some.com",
  },
  {
    firstName: "Alexandra",
    lastName: "Spalato",
    avatarUrl: "https://sessionize.com/image/c8c3-400o400o2-PR5UsgApAVEADZRixV4H8e.jpeg",
    email: "alexadark@some.com",
  },
  {
    firstName: "Cat",
    lastName: "Johnson",
    avatarUrl: "https://sessionize.com/image/7594-400o400o2-hWtdCjbdFdLgE2vEXBJtyo.jpg",
    email: "cat.j@some.com",
  },
  {
    firstName: "Ashley",
    lastName: "Narcisse",
    avatarUrl: "https://sessionize.com/image/5636-400o400o2-TWgi8vELMFoB3hB9uPw62d.jpg",
    email: "darkfadr@some.com",
  },
  {
    firstName: "Edmund",
    lastName: "Hung",
    avatarUrl: "https://sessionize.com/image/6aeb-400o400o2-Q5tAiuzKGgzSje9ZsK3Yu5.JPG",
    email: "edmundhung@some.com",
  },
  {
    firstName: "Clifford",
    lastName: "Fajardo",
    avatarUrl: "https://sessionize.com/image/30f1-400o400o2-wJBdJ6sFayjKmJycYKoHSe.jpg",
    email: "cliffordfajard0@some.com",
  },
  {
    firstName: "Erick",
    lastName: "Tamayo",
    avatarUrl: "https://sessionize.com/image/6faa-400o400o2-amseBRDkdg7wSK5tjsFDiG.jpg",
    email: "ericktamayo@some.com",
  },
  {
    firstName: "Paul",
    lastName: "Bratslavsky",
    avatarUrl: "https://sessionize.com/image/feba-400o400o2-R4GE7eqegJNFf3cQ567obs.jpg",
    email: "codingthirty@some.com",
  },
  {
    firstName: "Pedro",
    lastName: "Cattori",
    avatarUrl: "https://sessionize.com/image/c315-400o400o2-spjM5A6VVfVNnQsuwvX3DY.jpg",
    email: "pcattori@some.com",
  },
  {
    firstName: "Andre",
    lastName: "Landgraf",
    avatarUrl: "https://sessionize.com/image/eec1-400o400o2-HkvWKLFqecmFxLwqR9KMRw.jpg",
    email: "AndreLandgraf94@some.com",
  },
  {
    firstName: "Monica",
    lastName: "Powell",
    avatarUrl: "https://sessionize.com/image/c73a-400o400o2-4MTaTq6ftC15hqwtqUJmTC.jpg",
    email: "indigitalcolor@some.com",
  },
  {
    firstName: "Brian",
    lastName: "Lee",
    avatarUrl: "https://sessionize.com/image/cef7-400o400o2-KBZUydbjfkfGACQmjbHEvX.jpeg",
    email: "brian_dlee@some.com",
  },
  {
    firstName: "Sean",
    lastName: "McQuaid",
    avatarUrl: "https://sessionize.com/image/f83b-400o400o2-Pyw3chmeHMxGsNoj3nQmWU.jpg",
    email: "SeanMcQuaidCode@some.com",
  },
  {
    firstName: "Shane",
    lastName: "Walker",
    avatarUrl: "https://sessionize.com/image/a9fc-400o400o2-JHBnWZRoxp7QX74Hdac7AZ.jpg",
    email: "swalker326@some.com",
  },
  {
    firstName: "Jon",
    lastName: "Jensen",
    avatarUrl: "https://sessionize.com/image/6644-400o400o2-aHnGHb5Pdu3D32MbfrnQbj.jpg",
    email: "jenseng@some.com",
  },
];
