/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedContactsRouteImport } from './routes/_authed/contacts'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthedContactsIndexRouteImport } from './routes/_authed/contacts.index'
import { Route as AuthedContactsNewRouteImport } from './routes/_authed/contacts.new'
import { Route as AuthedContactsContactIdRouteImport } from './routes/_authed/contacts.$contactId'
import { Route as AuthedContactsContactIdEditRouteImport } from './routes/_authed/contacts.$contactId_.edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedContactsRoute = AuthedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedContactsIndexRoute = AuthedContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedContactsRoute,
} as any)
const AuthedContactsNewRoute = AuthedContactsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedContactsRoute,
} as any)
const AuthedContactsContactIdRoute = AuthedContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => AuthedContactsRoute,
} as any)
const AuthedContactsContactIdEditRoute =
  AuthedContactsContactIdEditRouteImport.update({
    id: '/$contactId_/edit',
    path: '/$contactId/edit',
    getParentRoute: () => AuthedContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/contacts': typeof AuthedContactsRouteWithChildren
  '/contacts/$contactId': typeof AuthedContactsContactIdRoute
  '/contacts/new': typeof AuthedContactsNewRoute
  '/contacts/': typeof AuthedContactsIndexRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/contacts/$contactId': typeof AuthedContactsContactIdRoute
  '/contacts/new': typeof AuthedContactsNewRoute
  '/contacts': typeof AuthedContactsIndexRoute
  '/contacts/$contactId/edit': typeof AuthedContactsContactIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authed/contacts': typeof AuthedContactsRouteWithChildren
  '/_authed/contacts/$contactId': typeof AuthedContactsContactIdRoute
  '/_authed/contacts/new': typeof AuthedContactsNewRoute
  '/_authed/contacts/': typeof AuthedContactsIndexRoute
  '/_authed/contacts/$contactId_/edit': typeof AuthedContactsContactIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contacts'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/contacts/'
    | '/contacts/$contactId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contacts/$contactId'
    | '/contacts/new'
    | '/contacts'
    | '/contacts/$contactId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_auth/login'
    | '/_authed/contacts'
    | '/_authed/contacts/$contactId'
    | '/_authed/contacts/new'
    | '/_authed/contacts/'
    | '/_authed/contacts/$contactId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/contacts/': {
      id: '/_authed/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedContactsIndexRouteImport
      parentRoute: typeof AuthedContactsRoute
    }
    '/_authed/contacts/new': {
      id: '/_authed/contacts/new'
      path: '/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AuthedContactsNewRouteImport
      parentRoute: typeof AuthedContactsRoute
    }
    '/_authed/contacts/$contactId': {
      id: '/_authed/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AuthedContactsContactIdRouteImport
      parentRoute: typeof AuthedContactsRoute
    }
    '/_authed/contacts/$contactId_/edit': {
      id: '/_authed/contacts/$contactId_/edit'
      path: '/$contactId/edit'
      fullPath: '/contacts/$contactId/edit'
      preLoaderRoute: typeof AuthedContactsContactIdEditRouteImport
      parentRoute: typeof AuthedContactsRoute
    }
  }
}

interface AuthedContactsRouteChildren {
  AuthedContactsContactIdRoute: typeof AuthedContactsContactIdRoute
  AuthedContactsNewRoute: typeof AuthedContactsNewRoute
  AuthedContactsIndexRoute: typeof AuthedContactsIndexRoute
  AuthedContactsContactIdEditRoute: typeof AuthedContactsContactIdEditRoute
}

const AuthedContactsRouteChildren: AuthedContactsRouteChildren = {
  AuthedContactsContactIdRoute: AuthedContactsContactIdRoute,
  AuthedContactsNewRoute: AuthedContactsNewRoute,
  AuthedContactsIndexRoute: AuthedContactsIndexRoute,
  AuthedContactsContactIdEditRoute: AuthedContactsContactIdEditRoute,
}

const AuthedContactsRouteWithChildren = AuthedContactsRoute._addFileChildren(
  AuthedContactsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedContactsRoute: typeof AuthedContactsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedContactsRoute: AuthedContactsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
